version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "frab-revalida"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gjc3zn5zqcfg"
s3_prefix = "frab-revalida"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

